spring:
  application:
    name: sv
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgresql://adrian:71fULydrMH3a4XH4EbMExkqPC0mYZmBG@dpg-d46jloje5dus73aruha0-a.oregon-postgres.render.com/sistema_voos_db
    username: adrian
    password: 71fULydrMH3a4XH4EbMExkqPC0mYZmBG

app:
  jwt:
    secret: ${JWT_SECRET:dGhpc2lzYXNhbXBsZWp3dHNlY3JldGtleWZvcnRlc3RpbmdwdXJwb3Nlc29ubHlwbGVhc2VyZXBsYWNlaW5wcm9kdWN0aW9u}
    expiration-ms: 86400000
    refresh-expiration-ms: 604800000
